// Las 30 recetas de ejemplo (de "txt comida.txt"), con proteína, ingredientes
// e instrucciones cortas para poder probar el generador de menú de una vez.
export const SEED_RECIPES = [
  // Guisados
  {
    name: "Tinga de pollo",
    category: "guisados",
    protein: "pollo",
    icon: "guisados",
    ingredients: "3 pechugas de pollo cocidas y deshebradas\n2 jitomates\n1/2 cebolla\n2 chiles chipotles adobados\n1 diente de ajo\nAceite, sal",
    instructions: "Licúa jitomate, chipotle, ajo y un poco del caldo de cocción. Acitrona la cebolla en aceite, agrega el licuado y deja sazonar 10 minutos. Incorpora el pollo deshebrado y cocina 10 minutos más a fuego bajo. Sirve con tostadas.",
  },
  {
    name: "Pollo en mole",
    category: "guisados",
    protein: "pollo",
    icon: "guisados",
    ingredients: "6 piezas de pollo\n200 g de mole en pasta\nCaldo de pollo\nAjonjolí para decorar",
    instructions: "Diluye el mole en pasta con caldo caliente hasta que quede terso. Cuece el pollo en la olla con la salsa de mole a fuego medio 25 minutos, moviendo para que no se pegue. Decora con ajonjolí.",
  },
  {
    name: "Pollo en adobo de guajillo",
    category: "guisados",
    protein: "pollo",
    icon: "guisados",
    ingredients: "6 piezas de pollo\n6 chiles guajillo\n2 jitomates\n1 diente de ajo\nComino, orégano, sal",
    instructions: "Hierve los chiles guajillo y licúa con jitomate, ajo y especias. Cuela la salsa, sazónala en una olla y agrega el pollo. Cocina tapado a fuego medio 30 minutos hasta que espese.",
  },
  {
    name: "Tampiqueña en salsa de guajillo",
    category: "guisados",
    protein: "carne",
    icon: "guisados",
    ingredients: "4 filetes de res delgados\n4 chiles guajillo\n2 jitomates\n1 diente de ajo\nSal y pimienta",
    instructions: "Prepara la salsa de guajillo hirviendo los chiles y licuando con jitomate y ajo. Sella los filetes en la plancha y báñalos con la salsa caliente al servir.",
  },
  {
    name: "Carne a la mexicana con papas",
    category: "guisados",
    protein: "carne",
    icon: "guisados",
    ingredients: "600 g de bistec de res en cubos\n2 papas en cubos\n2 jitomates picados\n1 cebolla picada\n2 chiles serranos",
    instructions: "Sofríe la carne hasta dorar y retira. En el mismo aceite acitrona cebolla, jitomate y chile. Regresa la carne, añade las papas y un poco de agua, tapa y cuece 20 minutos hasta que las papas estén suaves.",
  },
  {
    name: "Carne en su jugo",
    category: "guisados",
    protein: "carne",
    icon: "guisados",
    ingredients: "600 g de bistec de res finamente picado\n4 jitomates\n2 chiles serranos\n1/2 taza de frijoles de la olla\nTocino, cebolla y cilantro para decorar",
    instructions: "Licúa jitomate y chile con un poco de caldo. Fríe el tocino, agrega la carne y sella. Añade el licuado y los frijoles con su caldo, hierve 10 minutos. Sirve con cebolla y cilantro picados.",
  },
  {
    name: "Tortitas de carne deshebrada en salsa",
    category: "guisados",
    protein: "carne",
    icon: "guisados",
    ingredients: "400 g de carne deshebrada\n2 huevos\nPan molido\n4 jitomates para la salsa\n1 chile ancho",
    instructions: "Mezcla la carne deshebrada con huevo y forma tortitas, fríelas hasta dorar. Prepara una salsa licuando jitomate y chile ancho hervido, sazona y agrega las tortitas para que hiervan 10 minutos en la salsa.",
  },
  {
    name: "Hamburguesas caseras",
    category: "guisados",
    protein: "carne",
    icon: "guisados",
    ingredients: "600 g de carne molida de res\n1 huevo\nPan molido\nCebolla picada\nSal, pimienta, panes para hamburguesa",
    instructions: "Mezcla la carne con huevo, pan molido, cebolla y sazonadores. Forma las hamburguesas y cocina en sartén o plancha 4-5 minutos por lado. Arma con tus ingredientes favoritos.",
  },
  {
    name: "Fajitas de pollo",
    category: "guisados",
    protein: "pollo",
    icon: "guisados",
    ingredients: "4 pechugas de pollo en tiras\n1 pimiento rojo\n1 pimiento verde\n1 cebolla en tiras\nAjo, comino, limón",
    instructions: "Marina el pollo con ajo, comino y limón. Saltea a fuego alto hasta dorar, agrega los pimientos y la cebolla y cocina 5 minutos más sin que se suavicen de más.",
  },
  {
    name: "Tacos de pescado",
    category: "guisados",
    protein: "pescado",
    icon: "guisados",
    ingredients: "500 g de filete de pescado blanco\nHarina, cerveza o agua con gas para capear\nCol morada, mayonesa, limón\nTortillas de maíz",
    instructions: "Corta el pescado en tiras, capea con la mezcla de harina y fríe hasta dorar. Sirve en tortillas calientes con col, mayonesa y limón.",
  },
  {
    name: "Milanesas de res o pollo",
    category: "guisados",
    protein: "carne",
    icon: "guisados",
    ingredients: "4 milanesas de res o pollo\n2 huevos\nPan molido\nLimón, sal",
    instructions: "Sazona las milanesas, pásalas por huevo batido y luego por pan molido. Fríe en aceite caliente hasta dorar por ambos lados. Sirve con limón.",
  },
  {
    name: "Pechugas cordon bleu",
    category: "guisados",
    protein: "pollo",
    icon: "guisados",
    ingredients: "4 pechugas de pollo fileteadas\nJamón y queso para rellenar\nHarina, huevo, pan molido",
    instructions: "Rellena cada pechuga con jamón y queso, enróllala y asegura con palillos. Empaniza (harina, huevo, pan molido) y fríe hasta dorar por completo.",
  },
  {
    name: "Tacos dorados de pollo",
    category: "guisados",
    protein: "pollo",
    icon: "guisados",
    ingredients: "2 tazas de pollo cocido y deshebrado\n20 tortillas chicas\nAceite para freír\nLechuga, crema, queso",
    instructions: "Rellena las tortillas con el pollo, enróllalas y asegura con un palillo. Fríe en aceite caliente hasta dorar. Sirve con lechuga, crema y queso.",
  },

  // Sopas
  {
    name: "Sopa de tortilla",
    category: "sopas",
    protein: "ninguno",
    icon: "sopas",
    ingredients: "6 tortillas en tiras fritas\n4 jitomates\n1 diente de ajo\nCaldo de pollo\nChile pasilla, queso, aguacate para decorar",
    instructions: "Licúa jitomate y ajo, fríe el licuado y agrega el caldo. Hierve 10 minutos. Sirve con tiras de tortilla frita, queso, aguacate y chile pasilla.",
  },
  {
    name: "Sopa de lentejas",
    category: "sopas",
    protein: "ninguno",
    icon: "sopas",
    ingredients: "2 tazas de lentejas\n1 jitomate\n1/2 cebolla\n1 zanahoria\n1 plátano macho (opcional)",
    instructions: "Sofríe cebolla y jitomate picados, agrega las lentejas lavadas, la zanahoria y suficiente agua. Cuece 30-40 minutos hasta que las lentejas estén suaves.",
  },
  {
    name: "Sopa de verduras",
    category: "sopas",
    protein: "ninguno",
    icon: "sopas",
    ingredients: "Zanahoria, calabaza, papa y ejotes picados\n1 jitomate\nCaldo de pollo o verduras",
    instructions: "Sofríe el jitomate picado, agrega el caldo y las verduras. Cuece a fuego medio 20 minutos hasta que las verduras estén suaves.",
  },
  {
    name: "Sopa de chayote con verduras",
    category: "sopas",
    protein: "ninguno",
    icon: "sopas",
    ingredients: "2 chayotes en cubos\nZanahoria y calabaza\n1 jitomate\nCaldo de pollo",
    instructions: "Sofríe el jitomate, agrega el caldo y las verduras incluido el chayote. Cuece 20 minutos hasta que todo esté suave.",
  },
  {
    name: "Sopa de fideo",
    category: "sopas",
    protein: "ninguno",
    icon: "sopas",
    ingredients: "1 paquete de fideo\n2 jitomates\n1/4 de cebolla\nCaldo de pollo",
    instructions: "Fríe el fideo hasta dorar ligeramente. Licúa jitomate y cebolla, agrega al fideo junto con el caldo y cuece 10 minutos hasta que esté suave.",
  },

  // Guarniciones
  {
    name: "Arroz rojo",
    category: "guarniciones",
    protein: "ninguno",
    icon: "guarniciones",
    ingredients: "2 tazas de arroz\n2 jitomates\n1/4 de cebolla\n1 diente de ajo\nChícharos y zanahoria (opcional)",
    instructions: "Lava y escurre el arroz, fríelo ligeramente. Licúa jitomate, cebolla y ajo, agrega al arroz con caldo o agua. Cuece tapado a fuego bajo 20 minutos.",
  },
  {
    name: "Frijoles de la olla",
    category: "guarniciones",
    protein: "ninguno",
    icon: "guarniciones",
    ingredients: "2 tazas de frijoles\n1/4 de cebolla\nEpazote\nSal",
    instructions: "Lava los frijoles y cuece en olla exprés o normal con cebolla y epazote hasta que estén suaves. Sazona con sal al final de la cocción.",
  },
  {
    name: "Rajas con crema y queso",
    category: "guarniciones",
    protein: "ninguno",
    icon: "guarniciones",
    ingredients: "4 chiles poblanos asados y en rajas\n1 cebolla en tiras\nCrema\nQueso panela o manchego",
    instructions: "Acitrona la cebolla, agrega las rajas y saltea. Añade la crema y calienta sin dejar hervir fuerte. Agrega el queso al final para que se funda ligeramente.",
  },
  {
    name: "Verduras salteadas",
    category: "guarniciones",
    protein: "ninguno",
    icon: "guarniciones",
    ingredients: "Brócoli, zanahoria, calabaza y pimiento al gusto\nAjo picado\nAceite de oliva, sal",
    instructions: "Saltea el ajo en aceite caliente, agrega las verduras en trozos parejos y cocina a fuego alto moviendo constantemente 5-7 minutos, para que queden crujientes.",
  },
  {
    name: "Calabazas",
    category: "guarniciones",
    protein: "ninguno",
    icon: "guarniciones",
    ingredients: "4 calabazas en cubos\n1 jitomate picado\n1/4 de cebolla\nElote desgranado (opcional)",
    instructions: "Sofríe cebolla y jitomate, agrega las calabazas y el elote. Tapa y cuece a fuego medio 15 minutos hasta que las calabazas estén suaves.",
  },
  {
    name: "Papas al horno o como guarnición",
    category: "guarniciones",
    protein: "ninguno",
    icon: "guarniciones",
    ingredients: "4 papas medianas\nAceite de oliva\nSal, pimienta, orégano",
    instructions: "Corta las papas en gajos, báñalas en aceite y sazona. Hornea a 200°C por 30-35 minutos volteando a la mitad, hasta que doren.",
  },
  {
    name: "Ensaladas",
    category: "guarniciones",
    protein: "ninguno",
    icon: "guarniciones",
    ingredients: "Lechuga, jitomate, pepino y cebolla morada al gusto\nLimón, aceite de oliva, sal",
    instructions: "Lava y corta las verduras, mézclalas en un tazón. Aliña con limón, aceite de oliva y sal justo antes de servir.",
  },
  {
    name: "Sopes fritos",
    category: "guarniciones",
    protein: "ninguno",
    icon: "guarniciones",
    ingredients: "Masa de maíz\nFrijoles refritos\nLechuga, crema, queso, salsa",
    instructions: "Forma tortitas gruesas de masa, cuécelas en comal y pellizca el borde en caliente. Fríe ligeramente y cubre con frijoles, lechuga, crema, queso y salsa.",
  },

  // Salsas
  {
    name: "Salsa verde para chilaquiles",
    category: "salsas",
    protein: "ninguno",
    icon: "salsas_verde",
    ingredients: "8 tomates verdes\n2 chiles serranos\n1/4 de cebolla\n1 diente de ajo\nCilantro",
    instructions: "Hierve los tomates con chile hasta que cambien de color. Licúa con cebolla, ajo y cilantro. Sazona con sal.",
  },
  {
    name: "Salsa roja para chilaquiles",
    category: "salsas",
    protein: "ninguno",
    icon: "salsas_roja",
    ingredients: "6 jitomates\n2 chiles de árbol o guajillo\n1 diente de ajo\n1/4 de cebolla",
    instructions: "Hierve jitomate, chile y ajo hasta suavizar. Licúa con la cebolla y sazona con sal.",
  },
  {
    name: "Salsa verde para acompañar las comidas",
    category: "salsas",
    protein: "ninguno",
    icon: "salsas_verde",
    ingredients: "6 tomates verdes\n1-2 chiles serranos\nCilantro\n1/4 de cebolla",
    instructions: "Hierve los tomates con el chile, licúa con cebolla y cilantro crudos para una salsa más fresca. Sazona con sal.",
  },
  {
    name: "Adobo de guajillo preparado aparte",
    category: "salsas",
    protein: "ninguno",
    icon: "salsas_adobo",
    ingredients: "8 chiles guajillo\n2 dientes de ajo\nComino, orégano\nVinagre (opcional)",
    instructions: "Hierve los chiles guajillo hasta suavizar. Licúa con ajo, especias y un poco del agua de cocción hasta obtener una pasta tersa. Cuela y guarda para adobar carnes.",
  },
];
